baseURL = "https://__VERIFICATION_HUGO_BASE_URL__"
defaultContentLanguage = "de"
theme = "ubirch_verifier"

[languages]
[languages.de]
languageName = "Deutsch"
contentDir = "content/de"
weight = 1
[languages.de.params]
title = "Verifizierung"

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 2
[languages.en.params]
title = "Verification"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
verificationScriptUrl = "https://__VERIFICATION_SCRIPT_URL__"
verificationV2ScriptUrl = "https://__VERIFICATION_V2_SCRIPT_URL__"
disclaimer = "__SHOW_DEMO_DISCLAIMER__"
