baseURL = "https://verify.govdigital.de/"
defaultContentLanguage = "de"
theme = "ubirch_verifier"

[languages]
[languages.de]
languageName = "Deutsch"
contentDir = "content/de"
weight = 1
[languages.de.params]
title = "Verifizierung"

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 2
[languages.en.params]
title = "Verification"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
stage = "dev"
verificationScriptUrl = "http://localhost:9101/libs/verification/verification.js"
verificationV2ScriptUrl = "http://localhost:9101/libs/verification/verification-v2.js"
disclaimer = "demo"
