baseURL = "http://example.org/"
defaultContentLanguage = "de"
title = "ubirch Verification"
theme = "starter"

[languages]
  [languages.de]
    languageName = "Deutsch"
    contentDir = "content/de"
    weight = 1

  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
