---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data/v
  label: 'General-Data: Images, Colors, Styles, etc.'
  create: documents
  match: "*.json"
  new_doc_ext: json
  templates:
  - general-verification-data
- type: directory
  path: content/en
  label: English Pages
  create: documents
  match: "**/*"
  templates:
  - laboratory-verification-text-fields
- type: directory
  path: content/de
  label: Deutsche Seiten
  create: documents
  match: "**/*"
  templates:
  - laboratory-verification-text-fields
- type: directory
  path: data/formfields
  label: Form Fields Translations
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - form-fields-translation
- type: directory
  path: content
  label: Other Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.79.0
